# Generated by Django 3.0 on 2020-02-28 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=18),
        ),
        migrations.AlterModelTable(
            name='student',
            table='students',
        ),
    ]
